apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "metrics-server.fullname" . }}
  labels:
    app: {{ template "metrics-server.name" . }}
    chart: {{ template "metrics-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "metrics-server.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "metrics-server.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "metrics-server.serviceAccountName" . }}
      containers:
        - name: metrics-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /metrics-server
            {{- if .Values.insecureSkipVerify }}
            - --kubelet-insecure-tls
            {{- end }}
            {{- if .Values.tls.enabled }}
            - --client-ca-file
            - /certs/caFile
            - --tls-cert-file
            - /certs/certFile
            - --tls-private-key-file
            - /certs/privateKeyFile
            {{- end }}
            {{- range .Values.args }}
            - {{ . | quote }}
            {{- end }}
        {{- with .Values.resources }}
          resources:
{{ toYaml . | indent 12 }}
        {{- end }}
      {{- if .Values.tls.enabled }}
          volumeMounts:
            - mountPath: /certs/caFile
              name: ca-file
              readOnly: true
            - mountPath: /certs/certFile
              name: cert-file
              readOnly: true
            - mountPath: /certs/privateKeyFile
              name: key-file
              readOnly: true
      volumes:
        - name: ca-file
          hostPath:
            path: {{ .Values.tls.ca }}
        - name: cert-file
          hostPath:
            path: {{ .Values.tls.certificate }}
        - name: key-file
          hostPath:
            path: {{ .Values.tls.key }}
      {{- end}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
